[build]
  publish = "."
  command = "echo 'No build step required for static deploy'"

[[redirects]]
  from = "/admin"
  to = "/dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/employee"
  to = "/employee.html"
  status = 200
  force = true

[[redirects]]
  from = "/pos"
  to = "/pos.html"
  status = 200
  force = true

[[redirects]]
  from = "/ticket"
  to = "/ticket.html"
  status = 200
  force = true

[[redirects]]
  from = "/mobile-pos"
  to = "/mobile-pos.html"
  status = 200
  force = true

[[redirects]]
  from = "/productos"
  to = "/productos.html"
  status = 200
  force = true

[[redirects]]
  from = "/ventas"
  to = "/ventas.html"
  status = 200
  force = true

[[redirects]]
  from = "/usuarios"
  to = "/usuarios.html"
  status = 200
  force = true

[[redirects]]
  from = "/reportes"
  to = "/reportes.html"
  status = 200
  force = true

[[redirects]]
  from = "/configuracion"
  to = "/configuracion.html"
  status = 200
  force = true

[[redirects]]
  from = "/marcas-categorias"
  to = "/marcas-categorias.html"
  status = 200
  force = true

[[redirects]]
  from = "/movimientos"
  to = "/movimientos.html"
  status = 200
  force = true

[[redirects]]
  from = "/proveedores"
  to = "/proveedores.html"
  status = 200
  force = true
